<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>colors</string>
	</array>
	<key>name</key>
	<string>Colors</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^(comment)$</string>
			<key>name</key>
			<string>comment.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.line)$</string>
			<key>name</key>
			<string>comment.line.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.line\.double-slash)$</string>
			<key>name</key>
			<string>comment.line.double-slash.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.line\.double-dash)$</string>
			<key>name</key>
			<string>comment.line.double-dash.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.line\.number-sign)$</string>
			<key>name</key>
			<string>comment.line.number-sign.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.line\.percentage)$</string>
			<key>name</key>
			<string>comment.line.percentage.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.block)$</string>
			<key>name</key>
			<string>comment.block.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(comment\.block\.documentation)$</string>
			<key>name</key>
			<string>comment.block.documentation.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant)$</string>
			<key>name</key>
			<string>constant.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant\.numeric)$</string>
			<key>name</key>
			<string>constant.numeric.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant\.character)$</string>
			<key>name</key>
			<string>constant.character.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant\.character\.escape)$</string>
			<key>name</key>
			<string>constant.character.escape.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant\.language)$</string>
			<key>name</key>
			<string>constant.language.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(constant\.other)$</string>
			<key>name</key>
			<string>constant.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity)$</string>
			<key>name</key>
			<string>entity.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.name)$</string>
			<key>name</key>
			<string>entity.name.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.name\.function)$</string>
			<key>name</key>
			<string>entity.name.function.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.name\.type)$</string>
			<key>name</key>
			<string>entity.name.type.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.name\.tag)$</string>
			<key>name</key>
			<string>entity.name.tag.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.name\.section)$</string>
			<key>name</key>
			<string>entity.name.section.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.other\.inherited-class)$</string>
			<key>name</key>
			<string>entity.other.inherited-class.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(entity\.other\.attribute-name)$</string>
			<key>name</key>
			<string>entity.other.attribute-name.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(invalid)$</string>
			<key>name</key>
			<string>invalid.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(invalid\.illegal)$</string>
			<key>name</key>
			<string>invalid.illegal.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(invalid\.deprecated)$</string>
			<key>name</key>
			<string>invalid.deprecated.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(keyword)$</string>
			<key>name</key>
			<string>keyword.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(keyword\.control)$</string>
			<key>name</key>
			<string>keyword.control.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(keyword\.operator)$</string>
			<key>name</key>
			<string>keyword.operator.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(keyword\.other)$</string>
			<key>name</key>
			<string>keyword.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup)$</string>
			<key>name</key>
			<string>markup.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.underline)$</string>
			<key>name</key>
			<string>markup.underline.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.underline\.link)$</string>
			<key>name</key>
			<string>markup.underline.link.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.bold)$</string>
			<key>name</key>
			<string>markup.bold.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading)$</string>
			<key>name</key>
			<string>markup.heading.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.1)$</string>
			<key>name</key>
			<string>markup.heading.1.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.2)$</string>
			<key>name</key>
			<string>markup.heading.2.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.3)$</string>
			<key>name</key>
			<string>markup.heading.3.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.4)$</string>
			<key>name</key>
			<string>markup.heading.4.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.5)$</string>
			<key>name</key>
			<string>markup.heading.5.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.6)$</string>
			<key>name</key>
			<string>markup.heading.6.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.heading\.7)$</string>
			<key>name</key>
			<string>markup.heading.7.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.italic)$</string>
			<key>name</key>
			<string>markup.italic.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.list)$</string>
			<key>name</key>
			<string>markup.list.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.list\.numbered)$</string>
			<key>name</key>
			<string>markup.list.numbered.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.list\.unnumbered)$</string>
			<key>name</key>
			<string>markup.list.unnumbered.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.quote)$</string>
			<key>name</key>
			<string>markup.quote.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.raw)$</string>
			<key>name</key>
			<string>markup.raw.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(markup\.other)$</string>
			<key>name</key>
			<string>markup.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(meta)$</string>
			<key>name</key>
			<string>meta.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(storage)$</string>
			<key>name</key>
			<string>storage.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(storage\.type)$</string>
			<key>name</key>
			<string>storage.type.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(storage\.modifier)$</string>
			<key>name</key>
			<string>storage.modifier.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string)$</string>
			<key>name</key>
			<string>string.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.quoted)$</string>
			<key>name</key>
			<string>string.quoted.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.quoted\.single)$</string>
			<key>name</key>
			<string>string.quoted.single.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.quoted\.double)$</string>
			<key>name</key>
			<string>string.quoted.double.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.quoted\.triple)$</string>
			<key>name</key>
			<string>string.quoted.triple.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.quoted\.other)$</string>
			<key>name</key>
			<string>string.quoted.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.unquoted)$</string>
			<key>name</key>
			<string>string.unquoted.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.interpolated)$</string>
			<key>name</key>
			<string>string.interpolated.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.regexp)$</string>
			<key>name</key>
			<string>string.regexp.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(string\.other)$</string>
			<key>name</key>
			<string>string.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support)$</string>
			<key>name</key>
			<string>support.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.function)$</string>
			<key>name</key>
			<string>support.function.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.class)$</string>
			<key>name</key>
			<string>support.class.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.type)$</string>
			<key>name</key>
			<string>support.type.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.constant)$</string>
			<key>name</key>
			<string>support.constant.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.variable)$</string>
			<key>name</key>
			<string>support.variable.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(support\.other)$</string>
			<key>name</key>
			<string>support.other.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(variable)$</string>
			<key>name</key>
			<string>variable.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(variable\.parameter)$</string>
			<key>name</key>
			<string>variable.parameter.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(variable\.language)$</string>
			<key>name</key>
			<string>variable.language.colors</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(variable\.other)$</string>
			<key>name</key>
			<string>variable.other.colors</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.colors</string>
	<key>uuid</key>
	<string>799c9e13-1bbd-450b-9cae-ad1efdb430a8</string>
</dict>
</plist>
